#ifndef SNAKE_RL_H
#define SNAKE_RL_H

/* -- raylib.h -- */
#include <raylib.h>

void rl_init_window(int width, int height, const char *title);
void rl_close_window(void);
bool rl_window_should_close(void);
bool rl_is_window_ready(void);
bool rl_is_window_fullscreen(void);
bool rl_is_window_hidden(void);
bool rl_is_window_minimized(void);
bool rl_is_window_maximized(void);
bool rl_is_window_focused(void);
bool rl_is_window_resized(void);
bool rl_is_window_state(unsigned int flag);
void rl_set_window_state(unsigned int flags);
void rl_clear_window_state(unsigned int flags);
void rl_toggle_fullscreen(void);
void rl_toggle_borderless_windowed(void);
void rl_maximize_window(void);
void rl_minimize_window(void);
void rl_restore_window(void);
void rl_set_window_icon(Image image);
void rl_set_window_icons(Image *images, int count);
void rl_set_window_title(const char *title);
void rl_set_window_position(int x, int y);
void rl_set_window_monitor(int monitor);
void rl_set_window_min_size(int width, int height);
void rl_set_window_max_size(int width, int height);
void rl_set_window_size(int width, int height);
void rl_set_window_opacity(float opacity);
void rl_set_window_focused(void);
int rl_get_screen_width(void);
int rl_get_screen_height(void);
int rl_get_render_width(void);
int rl_get_render_height(void);
int rl_get_monitor_count(void);
int rl_get_current_monitor(void);
Vector2 rl_get_monitor_position(int monitor);
int rl_get_monitor_width(int monitor);
int rl_get_monitor_height(int monitor);
int rl_get_monitor_physical_width(int monitor);
int rl_get_monitor_physical_height(int monitor);
int rl_get_monitor_refresh_rate(int monitor);
Vector2 rl_get_window_position(void);
Vector2 rl_get_window_scale_dpi(void);
void rl_set_clipboard_text(const char *text);
Image rl_get_clipboard_image(void);
void rl_enable_event_waiting(void);
void rl_disable_event_waiting(void);
void rl_show_cursor(void);
void rl_hide_cursor(void);
bool rl_is_cursor_hidden(void);
void rl_enable_cursor(void);
void rl_disable_cursor(void);
bool rl_is_cursor_on_screen(void);
void rl_clear_background(Color color);
void rl_begin_drawing(void);
void rl_end_drawing(void);
void rl_begin_mode2_d(Camera2D camera);
void rl_end_mode2_d(void);
void rl_begin_mode3_d(Camera3D camera);
void rl_end_mode3_d(void);
void rl_begin_texture_mode(RenderTexture2D target);
void rl_end_texture_mode(void);
void rl_begin_shader_mode(Shader shader);
void rl_end_shader_mode(void);
void rl_begin_blend_mode(int mode);
void rl_end_blend_mode(void);
void rl_begin_scissor_mode(int x, int y, int width, int height);
void rl_end_scissor_mode(void);
void rl_begin_vr_stereo_mode(VrStereoConfig config);
void rl_end_vr_stereo_mode(void);
VrStereoConfig rl_load_vr_stereo_config(VrDeviceInfo device);
void rl_unload_vr_stereo_config(VrStereoConfig config);
Shader rl_load_shader(const char *vsFileName, const char *fsFileName);
Shader rl_load_shader_from_memory(const char *vsCode, const char *fsCode);
bool rl_is_shader_valid(Shader shader);
int rl_get_shader_location(Shader shader, const char *uniformName);
int rl_get_shader_location_attrib(Shader shader, const char *attribName);
void rl_set_shader_value(Shader shader, int locIndex, const void *value, int uniformType);
void rl_set_shader_value_v(Shader shader, int locIndex, const void *value, int uniformType, int count);
void rl_set_shader_value_matrix(Shader shader, int locIndex, Matrix mat);
void rl_set_shader_value_texture(Shader shader, int locIndex, Texture2D texture);
void rl_unload_shader(Shader shader);
Ray rl_get_screen_to_world_ray(Vector2 position, Camera camera);
Ray rl_get_screen_to_world_ray_ex(Vector2 position, Camera camera, int width, int height);
Vector2 rl_get_world_to_screen(Vector3 position, Camera camera);
Vector2 rl_get_world_to_screen_ex(Vector3 position, Camera camera, int width, int height);
Vector2 rl_get_world_to_screen2_d(Vector2 position, Camera2D camera);
Vector2 rl_get_screen_to_world2_d(Vector2 position, Camera2D camera);
Matrix rl_get_camera_matrix(Camera camera);
Matrix rl_get_camera_matrix2_d(Camera2D camera);
void rl_set_target_fps(int fps);
float rl_get_frame_time(void);
double rl_get_time(void);
int rl_get_fps(void);
void rl_swap_screen_buffer(void);
void rl_poll_input_events(void);
void rl_wait_time(double seconds);
void rl_set_random_seed(unsigned int seed);
int rl_get_random_value(int min, int max);
void rl_unload_random_sequence(int *sequence);
void rl_take_screenshot(const char *fileName);
void rl_set_config_flags(unsigned int flags);
void rl_open_url(const char *url);
void rl_set_trace_log_level(int logLevel);
#define rl_trace_log(...) TraceLog(__VA_ARGS__)
void rl_set_trace_log_callback(TraceLogCallback callback);
void rl_mem_free(void *ptr);
void rl_unload_file_data(unsigned char *data);
bool rl_save_file_data(const char *fileName, const void *data, int dataSize);
bool rl_export_data_as_code(const unsigned char *data, int dataSize, const char *fileName);
void rl_unload_file_text(char *text);
bool rl_save_file_text(const char *fileName, const char *text);
void rl_set_load_file_data_callback(LoadFileDataCallback callback);
void rl_set_save_file_data_callback(SaveFileDataCallback callback);
void rl_set_load_file_text_callback(LoadFileTextCallback callback);
void rl_set_save_file_text_callback(SaveFileTextCallback callback);
int rl_file_rename(const char *fileName, const char *fileRename);
int rl_file_remove(const char *fileName);
int rl_file_copy(const char *srcPath, const char *dstPath);
int rl_file_move(const char *srcPath, const char *dstPath);
int rl_file_text_replace(const char *fileName, const char *search, const char *replacement);
int rl_file_text_find_index(const char *fileName, const char *search);
bool rl_file_exists(const char *fileName);
bool rl_directory_exists(const char *dirPath);
bool rl_is_file_extension(const char *fileName, const char *ext);
int rl_get_file_length(const char *fileName);
long rl_get_file_mod_time(const char *fileName);
int rl_make_directory(const char *dirPath);
bool rl_change_directory(const char *dirPath);
bool rl_is_path_file(const char *path);
bool rl_is_file_name_valid(const char *fileName);
FilePathList rl_load_directory_files(const char *dirPath);
FilePathList rl_load_directory_files_ex(const char *basePath, const char *filter, bool scanSubdirs);
void rl_unload_directory_files(FilePathList files);
bool rl_is_file_dropped(void);
FilePathList rl_load_dropped_files(void);
void rl_unload_dropped_files(FilePathList files);
unsigned int rl_get_directory_file_count(const char *dirPath);
unsigned int rl_get_directory_file_count_ex(const char *basePath, const char *filter, bool scanSubdirs);
unsigned int rl_compute_crc32(const unsigned char *data, int dataSize);
AutomationEventList rl_load_automation_event_list(const char *fileName);
void rl_unload_automation_event_list(AutomationEventList list);
bool rl_export_automation_event_list(AutomationEventList list, const char *fileName);
void rl_set_automation_event_list(AutomationEventList *list);
void rl_set_automation_event_base_frame(int frame);
void rl_start_automation_event_recording(void);
void rl_stop_automation_event_recording(void);
void rl_play_automation_event(AutomationEvent event);
bool rl_is_key_pressed(int key);
bool rl_is_key_pressed_repeat(int key);
bool rl_is_key_down(int key);
bool rl_is_key_released(int key);
bool rl_is_key_up(int key);
int rl_get_key_pressed(void);
int rl_get_char_pressed(void);
void rl_set_exit_key(int key);
bool rl_is_gamepad_available(int gamepad);
bool rl_is_gamepad_button_pressed(int gamepad, int button);
bool rl_is_gamepad_button_down(int gamepad, int button);
bool rl_is_gamepad_button_released(int gamepad, int button);
bool rl_is_gamepad_button_up(int gamepad, int button);
int rl_get_gamepad_button_pressed(void);
int rl_get_gamepad_axis_count(int gamepad);
float rl_get_gamepad_axis_movement(int gamepad, int axis);
int rl_set_gamepad_mappings(const char *mappings);
void rl_set_gamepad_vibration(int gamepad, float leftMotor, float rightMotor, float duration);
bool rl_is_mouse_button_pressed(int button);
bool rl_is_mouse_button_down(int button);
bool rl_is_mouse_button_released(int button);
bool rl_is_mouse_button_up(int button);
int rl_get_mouse_x(void);
int rl_get_mouse_y(void);
Vector2 rl_get_mouse_position(void);
Vector2 rl_get_mouse_delta(void);
void rl_set_mouse_position(int x, int y);
void rl_set_mouse_offset(int offsetX, int offsetY);
void rl_set_mouse_scale(float scaleX, float scaleY);
float rl_get_mouse_wheel_move(void);
Vector2 rl_get_mouse_wheel_move_v(void);
void rl_set_mouse_cursor(int cursor);
int rl_get_touch_x(void);
int rl_get_touch_y(void);
Vector2 rl_get_touch_position(int index);
int rl_get_touch_point_id(int index);
int rl_get_touch_point_count(void);
void rl_set_gestures_enabled(unsigned int flags);
bool rl_is_gesture_detected(unsigned int gesture);
int rl_get_gesture_detected(void);
float rl_get_gesture_hold_duration(void);
Vector2 rl_get_gesture_drag_vector(void);
float rl_get_gesture_drag_angle(void);
Vector2 rl_get_gesture_pinch_vector(void);
float rl_get_gesture_pinch_angle(void);
void rl_update_camera(Camera *camera, int mode);
void rl_update_camera_pro(Camera *camera, Vector3 movement, Vector3 rotation, float zoom);
void rl_set_shapes_texture(Texture2D texture, Rectangle source);
Texture2D rl_get_shapes_texture(void);
Rectangle rl_get_shapes_texture_rectangle(void);
void rl_draw_pixel(int posX, int posY, Color color);
void rl_draw_pixel_v(Vector2 position, Color color);
void rl_draw_line(int startPosX, int startPosY, int endPosX, int endPosY, Color color);
void rl_draw_line_v(Vector2 startPos, Vector2 endPos, Color color);
void rl_draw_line_ex(Vector2 startPos, Vector2 endPos, float thick, Color color);
void rl_draw_line_strip(const Vector2 *points, int pointCount, Color color);
void rl_draw_line_bezier(Vector2 startPos, Vector2 endPos, float thick, Color color);
void rl_draw_line_dashed(Vector2 startPos, Vector2 endPos, int dashSize, int spaceSize, Color color);
void rl_draw_circle(int centerX, int centerY, float radius, Color color);
void rl_draw_circle_v(Vector2 center, float radius, Color color);
void rl_draw_circle_gradient(Vector2 center, float radius, Color inner, Color outer);
void rl_draw_circle_sector(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color);
void rl_draw_circle_sector_lines(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color);
void rl_draw_circle_lines(int centerX, int centerY, float radius, Color color);
void rl_draw_circle_lines_v(Vector2 center, float radius, Color color);
void rl_draw_ellipse(int centerX, int centerY, float radiusH, float radiusV, Color color);
void rl_draw_ellipse_v(Vector2 center, float radiusH, float radiusV, Color color);
void rl_draw_ellipse_lines(int centerX, int centerY, float radiusH, float radiusV, Color color);
void rl_draw_ellipse_lines_v(Vector2 center, float radiusH, float radiusV, Color color);
void rl_draw_ring(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color);
void rl_draw_ring_lines(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color);
void rl_draw_rectangle(int posX, int posY, int width, int height, Color color);
void rl_draw_rectangle_v(Vector2 position, Vector2 size, Color color);
void rl_draw_rectangle_rec(Rectangle rec, Color color);
void rl_draw_rectangle_pro(Rectangle rec, Vector2 origin, float rotation, Color color);
void rl_draw_rectangle_gradient_v(int posX, int posY, int width, int height, Color top, Color bottom);
void rl_draw_rectangle_gradient_h(int posX, int posY, int width, int height, Color left, Color right);
void rl_draw_rectangle_gradient_ex(Rectangle rec, Color topLeft, Color bottomLeft, Color bottomRight, Color topRight);
void rl_draw_rectangle_lines(int posX, int posY, int width, int height, Color color);
void rl_draw_rectangle_lines_ex(Rectangle rec, float lineThick, Color color);
void rl_draw_rectangle_rounded(Rectangle rec, float roundness, int segments, Color color);
void rl_draw_rectangle_rounded_lines(Rectangle rec, float roundness, int segments, Color color);
void rl_draw_rectangle_rounded_lines_ex(Rectangle rec, float roundness, int segments, float lineThick, Color color);
void rl_draw_triangle(Vector2 v1, Vector2 v2, Vector2 v3, Color color);
void rl_draw_triangle_gradient(Vector2 v1, Vector2 v2, Vector2 v3, Color c1, Color c2, Color c3);
void rl_draw_triangle_lines(Vector2 v1, Vector2 v2, Vector2 v3, Color color);
void rl_draw_triangle_fan(const Vector2 *points, int pointCount, Color color);
void rl_draw_triangle_strip(const Vector2 *points, int pointCount, Color color);
void rl_draw_poly(Vector2 center, int sides, float radius, float rotation, Color color);
void rl_draw_poly_lines(Vector2 center, int sides, float radius, float rotation, Color color);
void rl_draw_poly_lines_ex(Vector2 center, int sides, float radius, float rotation, float lineThick, Color color);
void rl_draw_spline_linear(const Vector2 *points, int pointCount, float thick, Color color);
void rl_draw_spline_basis(const Vector2 *points, int pointCount, float thick, Color color);
void rl_draw_spline_catmull_rom(const Vector2 *points, int pointCount, float thick, Color color);
void rl_draw_spline_bezier_quadratic(const Vector2 *points, int pointCount, float thick, Color color);
void rl_draw_spline_bezier_cubic(const Vector2 *points, int pointCount, float thick, Color color);
void rl_draw_spline_segment_linear(Vector2 p1, Vector2 p2, float thick, Color color);
void rl_draw_spline_segment_basis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color);
void rl_draw_spline_segment_catmull_rom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color);
void rl_draw_spline_segment_bezier_quadratic(Vector2 p1, Vector2 c2, Vector2 p3, float thick, Color color);
void rl_draw_spline_segment_bezier_cubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float thick, Color color);
Vector2 rl_get_spline_point_linear(Vector2 startPos, Vector2 endPos, float t);
Vector2 rl_get_spline_point_basis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float t);
Vector2 rl_get_spline_point_catmull_rom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float t);
Vector2 rl_get_spline_point_bezier_quadratic(Vector2 p1, Vector2 c2, Vector2 p3, float t);
Vector2 rl_get_spline_point_bezier_cubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float t);
bool rl_check_collision_recs(Rectangle rec1, Rectangle rec2);
bool rl_check_collision_circles(Vector2 center1, float radius1, Vector2 center2, float radius2);
bool rl_check_collision_circle_rec(Vector2 center, float radius, Rectangle rec);
bool rl_check_collision_circle_line(Vector2 center, float radius, Vector2 p1, Vector2 p2);
bool rl_check_collision_point_rec(Vector2 point, Rectangle rec);
bool rl_check_collision_point_circle(Vector2 point, Vector2 center, float radius);
bool rl_check_collision_point_triangle(Vector2 point, Vector2 p1, Vector2 p2, Vector2 p3);
bool rl_check_collision_point_line(Vector2 point, Vector2 p1, Vector2 p2, int threshold);
bool rl_check_collision_point_poly(Vector2 point, const Vector2 *points, int pointCount);
bool rl_check_collision_lines(Vector2 startPos1, Vector2 endPos1, Vector2 startPos2, Vector2 endPos2, Vector2 *collisionPoint);
Rectangle rl_get_collision_rec(Rectangle rec1, Rectangle rec2);
Image rl_load_image(const char *fileName);
Image rl_load_image_raw(const char *fileName, int width, int height, int format, int headerSize);
Image rl_load_image_anim(const char *fileName, int *frames);
Image rl_load_image_anim_from_memory(const char *fileType, const unsigned char *fileData, int dataSize, int *frames);
Image rl_load_image_from_memory(const char *fileType, const unsigned char *fileData, int dataSize);
Image rl_load_image_from_texture(Texture2D texture);
Image rl_load_image_from_screen(void);
bool rl_is_image_valid(Image image);
void rl_unload_image(Image image);
bool rl_export_image(Image image, const char *fileName);
bool rl_export_image_as_code(Image image, const char *fileName);
Image rl_gen_image_color(int width, int height, Color color);
Image rl_gen_image_gradient_linear(int width, int height, int direction, Color start, Color end);
Image rl_gen_image_gradient_radial(int width, int height, float density, Color inner, Color outer);
Image rl_gen_image_gradient_square(int width, int height, float density, Color inner, Color outer);
Image rl_gen_image_checked(int width, int height, int checksX, int checksY, Color col1, Color col2);
Image rl_gen_image_white_noise(int width, int height, float factor);
Image rl_gen_image_perlin_noise(int width, int height, int offsetX, int offsetY, float scale);
Image rl_gen_image_cellular(int width, int height, int tileSize);
Image rl_gen_image_text(int width, int height, const char *text);
Image rl_image_copy(Image image);
Image rl_image_from_image(Image image, Rectangle rec);
Image rl_image_from_channel(Image image, int selectedChannel);
Image rl_image_text(const char *text, int fontSize, Color color);
Image rl_image_text_ex(Font font, const char *text, float fontSize, float spacing, Color tint);
void rl_image_format(Image *image, int newFormat);
void rl_image_to_pot(Image *image, Color fill);
void rl_image_crop(Image *image, Rectangle crop);
void rl_image_alpha_crop(Image *image, float threshold);
void rl_image_alpha_clear(Image *image, Color color, float threshold);
void rl_image_alpha_mask(Image *image, Image alphaMask);
void rl_image_alpha_premultiply(Image *image);
void rl_image_blur_gaussian(Image *image, int blurSize);
void rl_image_kernel_convolution(Image *image, const float *kernel, int kernelSize);
void rl_image_resize(Image *image, int newWidth, int newHeight);
void rl_image_resize_nn(Image *image, int newWidth, int newHeight);
void rl_image_resize_canvas(Image *image, int newWidth, int newHeight, int offsetX, int offsetY, Color fill);
void rl_image_mipmaps(Image *image);
void rl_image_dither(Image *image, int rBpp, int gBpp, int bBpp, int aBpp);
void rl_image_flip_vertical(Image *image);
void rl_image_flip_horizontal(Image *image);
void rl_image_rotate(Image *image, int degrees);
void rl_image_rotate_cw(Image *image);
void rl_image_rotate_ccw(Image *image);
void rl_image_color_tint(Image *image, Color color);
void rl_image_color_invert(Image *image);
void rl_image_color_grayscale(Image *image);
void rl_image_color_contrast(Image *image, int contrast);
void rl_image_color_brightness(Image *image, int brightness);
void rl_image_color_replace(Image *image, Color color, Color replace);
void rl_unload_image_colors(Color *colors);
void rl_unload_image_palette(Color *colors);
Rectangle rl_get_image_alpha_border(Image image, float threshold);
Color rl_get_image_color(Image image, int x, int y);
void rl_image_clear_background(Image *dst, Color color);
void rl_image_draw_pixel(Image *dst, int posX, int posY, Color color);
void rl_image_draw_pixel_v(Image *dst, Vector2 position, Color color);
void rl_image_draw_line(Image *dst, int startPosX, int startPosY, int endPosX, int endPosY, Color color);
void rl_image_draw_line_v(Image *dst, Vector2 start, Vector2 end, Color color);
void rl_image_draw_line_ex(Image *dst, Vector2 start, Vector2 end, int thick, Color color);
void rl_image_draw_circle(Image *dst, int centerX, int centerY, int radius, Color color);
void rl_image_draw_circle_v(Image *dst, Vector2 center, int radius, Color color);
void rl_image_draw_circle_lines(Image *dst, int centerX, int centerY, int radius, Color color);
void rl_image_draw_circle_lines_v(Image *dst, Vector2 center, int radius, Color color);
void rl_image_draw_rectangle(Image *dst, int posX, int posY, int width, int height, Color color);
void rl_image_draw_rectangle_v(Image *dst, Vector2 position, Vector2 size, Color color);
void rl_image_draw_rectangle_rec(Image *dst, Rectangle rec, Color color);
void rl_image_draw_rectangle_lines(Image *dst, int posX, int posY, int width, int height, Color color);
void rl_image_draw_rectangle_lines_ex(Image *dst, Rectangle rec, int thick, Color color);
void rl_image_draw_triangle(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color);
void rl_image_draw_triangle_gradient(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color c1, Color c2, Color c3);
void rl_image_draw_triangle_lines(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color);
void rl_image_draw_triangle_fan(Image *dst, const Vector2 *points, int pointCount, Color color);
void rl_image_draw_triangle_strip(Image *dst, const Vector2 *points, int pointCount, Color color);
void rl_image_draw(Image *dst, Image src, Rectangle srcRec, Rectangle dstRec, Color tint);
void rl_image_draw_text(Image *dst, const char *text, int posX, int posY, int fontSize, Color color);
void rl_image_draw_text_ex(Image *dst, Font font, const char *text, Vector2 position, float fontSize, float spacing, Color tint);
Texture2D rl_load_texture(const char *fileName);
Texture2D rl_load_texture_from_image(Image image);
TextureCubemap rl_load_texture_cubemap(Image image, int layout);
RenderTexture2D rl_load_render_texture(int width, int height);
bool rl_is_texture_valid(Texture2D texture);
void rl_unload_texture(Texture2D texture);
bool rl_is_render_texture_valid(RenderTexture2D target);
void rl_unload_render_texture(RenderTexture2D target);
void rl_update_texture(Texture2D texture, const void *pixels);
void rl_update_texture_rec(Texture2D texture, Rectangle rec, const void *pixels);
void rl_gen_texture_mipmaps(Texture2D *texture);
void rl_set_texture_filter(Texture2D texture, int filter);
void rl_set_texture_wrap(Texture2D texture, int wrap);
void rl_draw_texture(Texture2D texture, int posX, int posY, Color tint);
void rl_draw_texture_v(Texture2D texture, Vector2 position, Color tint);
void rl_draw_texture_ex(Texture2D texture, Vector2 position, float rotation, float scale, Color tint);
void rl_draw_texture_rec(Texture2D texture, Rectangle source, Vector2 position, Color tint);
void rl_draw_texture_pro(Texture2D texture, Rectangle source, Rectangle dest, Vector2 origin, float rotation, Color tint);
void rl_draw_texture_n_patch(Texture2D texture, NPatchInfo nPatchInfo, Rectangle dest, Vector2 origin, float rotation, Color tint);
bool rl_color_is_equal(Color col1, Color col2);
Color rl_fade(Color color, float alpha);
int rl_color_to_int(Color color);
Vector4 rl_color_normalize(Color color);
Color rl_color_from_normalized(Vector4 normalized);
Vector3 rl_color_to_hsv(Color color);
Color rl_color_from_hsv(float hue, float saturation, float value);
Color rl_color_tint(Color color, Color tint);
Color rl_color_brightness(Color color, float factor);
Color rl_color_contrast(Color color, float contrast);
Color rl_color_alpha(Color color, float alpha);
Color rl_color_alpha_blend(Color dst, Color src, Color tint);
Color rl_color_lerp(Color color1, Color color2, float factor);
Color rl_get_color(unsigned int hexValue);
Color rl_get_pixel_color(void *srcPtr, int format);
void rl_set_pixel_color(void *dstPtr, Color color, int format);
int rl_get_pixel_data_size(int width, int height, int format);
Font rl_get_font_default(void);
Font rl_load_font(const char *fileName);
Font rl_load_font_ex(const char *fileName, int fontSize, const int *codepoints, int codepointCount);
Font rl_load_font_from_image(Image image, Color key, int firstChar);
Font rl_load_font_from_memory(const char *fileType, const unsigned char *fileData, int dataSize, int fontSize, const int *codepoints, int codepointCount);
bool rl_is_font_valid(Font font);
Image rl_gen_image_font_atlas(const GlyphInfo *glyphs, Rectangle **glyphRecs, int glyphCount, int fontSize, int padding, int packMethod);
void rl_unload_font_data(GlyphInfo *glyphs, int glyphCount);
void rl_unload_font(Font font);
bool rl_export_font_as_code(Font font, const char *fileName);
void rl_draw_fps(int posX, int posY);
void rl_draw_text(const char *text, int posX, int posY, int fontSize, Color color);
void rl_draw_text_ex(Font font, const char *text, Vector2 position, float fontSize, float spacing, Color tint);
void rl_draw_text_pro(Font font, const char *text, Vector2 position, Vector2 origin, float rotation, float fontSize, float spacing, Color tint);
void rl_draw_text_codepoint(Font font, int codepoint, Vector2 position, float fontSize, Color tint);
void rl_draw_text_codepoints(Font font, const int *codepoints, int codepointCount, Vector2 position, float fontSize, float spacing, Color tint);
void rl_set_text_line_spacing(int spacing);
int rl_measure_text(const char *text, int fontSize);
Vector2 rl_measure_text_ex(Font font, const char *text, float fontSize, float spacing);
Vector2 rl_measure_text_codepoints(Font font, const int *codepoints, int length, float fontSize, float spacing);
int rl_get_glyph_index(Font font, int codepoint);
GlyphInfo rl_get_glyph_info(Font font, int codepoint);
Rectangle rl_get_glyph_atlas_rec(Font font, int codepoint);
void rl_unload_utf8(char *text);
void rl_unload_codepoints(int *codepoints);
int rl_get_codepoint_count(const char *text);
int rl_get_codepoint(const char *text, int *codepointSize);
int rl_get_codepoint_next(const char *text, int *codepointSize);
int rl_get_codepoint_previous(const char *text, int *codepointSize);
void rl_unload_text_lines(char **text, int lineCount);
int rl_text_copy(char *dst, const char *src);
bool rl_text_is_equal(const char *text1, const char *text2);
unsigned int rl_text_length(const char *text);
void rl_text_append(char *text, const char *append, int *position);
int rl_text_find_index(const char *text, const char *search);
int rl_text_to_integer(const char *text);
float rl_text_to_float(const char *text);
void rl_draw_line3_d(Vector3 startPos, Vector3 endPos, Color color);
void rl_draw_point3_d(Vector3 position, Color color);
void rl_draw_circle3_d(Vector3 center, float radius, Vector3 rotationAxis, float rotationAngle, Color color);
void rl_draw_triangle3_d(Vector3 v1, Vector3 v2, Vector3 v3, Color color);
void rl_draw_triangle_strip3_d(const Vector3 *points, int pointCount, Color color);
void rl_draw_cube(Vector3 position, float width, float height, float length, Color color);
void rl_draw_cube_v(Vector3 position, Vector3 size, Color color);
void rl_draw_cube_wires(Vector3 position, float width, float height, float length, Color color);
void rl_draw_cube_wires_v(Vector3 position, Vector3 size, Color color);
void rl_draw_sphere(Vector3 centerPos, float radius, Color color);
void rl_draw_sphere_ex(Vector3 centerPos, float radius, int rings, int slices, Color color);
void rl_draw_sphere_wires(Vector3 centerPos, float radius, int rings, int slices, Color color);
void rl_draw_cylinder(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color);
void rl_draw_cylinder_ex(Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color);
void rl_draw_cylinder_wires(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color);
void rl_draw_cylinder_wires_ex(Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int slices, Color color);
void rl_draw_capsule(Vector3 startPos, Vector3 endPos, float radius, int rings, int slices, Color color);
void rl_draw_capsule_wires(Vector3 startPos, Vector3 endPos, float radius, int rings, int slices, Color color);
void rl_draw_plane(Vector3 centerPos, Vector2 size, Color color);
void rl_draw_ray(Ray ray, Color color);
void rl_draw_grid(int slices, float spacing);
Model rl_load_model(const char *fileName);
Model rl_load_model_from_mesh(Mesh mesh);
bool rl_is_model_valid(Model model);
void rl_unload_model(Model model);
BoundingBox rl_get_model_bounding_box(Model model);
void rl_draw_model(Model model, Vector3 position, float scale, Color tint);
void rl_draw_model_ex(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint);
void rl_draw_model_wires(Model model, Vector3 position, float scale, Color tint);
void rl_draw_model_wires_ex(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint);
void rl_draw_bounding_box(BoundingBox box, Color color);
void rl_draw_billboard(Camera camera, Texture2D texture, Vector3 position, float scale, Color tint);
void rl_draw_billboard_rec(Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector2 size, Color tint);
void rl_draw_billboard_pro(Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector3 up, Vector2 size, Vector2 origin, float rotation, Color tint);
void rl_upload_mesh(Mesh *mesh, bool dynamic);
void rl_update_mesh_buffer(Mesh mesh, int index, const void *data, int dataSize, int offset);
void rl_unload_mesh(Mesh mesh);
void rl_draw_mesh(Mesh mesh, Material material, Matrix transform);
void rl_draw_mesh_instanced(Mesh mesh, Material material, const Matrix *transforms, int instances);
BoundingBox rl_get_mesh_bounding_box(Mesh mesh);
void rl_gen_mesh_tangents(Mesh *mesh);
bool rl_export_mesh(Mesh mesh, const char *fileName);
bool rl_export_mesh_as_code(Mesh mesh, const char *fileName);
Mesh rl_gen_mesh_poly(int sides, float radius);
Mesh rl_gen_mesh_plane(float width, float length, int resX, int resZ);
Mesh rl_gen_mesh_cube(float width, float height, float length);
Mesh rl_gen_mesh_sphere(float radius, int rings, int slices);
Mesh rl_gen_mesh_hemi_sphere(float radius, int rings, int slices);
Mesh rl_gen_mesh_cylinder(float radius, float height, int slices);
Mesh rl_gen_mesh_cone(float radius, float height, int slices);
Mesh rl_gen_mesh_torus(float radius, float size, int radSeg, int sides);
Mesh rl_gen_mesh_knot(float radius, float size, int radSeg, int sides);
Mesh rl_gen_mesh_heightmap(Image heightmap, Vector3 size);
Mesh rl_gen_mesh_cubicmap(Image cubicmap, Vector3 cubeSize);
Material rl_load_material_default(void);
bool rl_is_material_valid(Material material);
void rl_unload_material(Material material);
void rl_set_material_texture(Material *material, int mapType, Texture2D texture);
void rl_set_model_mesh_material(Model *model, int meshId, int materialId);
void rl_update_model_animation(Model model, ModelAnimation anim, float frame);
void rl_update_model_animation_ex(Model model, ModelAnimation animA, float frameA, ModelAnimation animB, float frameB, float blend);
void rl_unload_model_animations(ModelAnimation *animations, int animCount);
bool rl_is_model_animation_valid(Model model, ModelAnimation anim);
bool rl_check_collision_spheres(Vector3 center1, float radius1, Vector3 center2, float radius2);
bool rl_check_collision_boxes(BoundingBox box1, BoundingBox box2);
bool rl_check_collision_box_sphere(BoundingBox box, Vector3 center, float radius);
RayCollision rl_get_ray_collision_sphere(Ray ray, Vector3 center, float radius);
RayCollision rl_get_ray_collision_box(Ray ray, BoundingBox box);
RayCollision rl_get_ray_collision_mesh(Ray ray, Mesh mesh, Matrix transform);
RayCollision rl_get_ray_collision_triangle(Ray ray, Vector3 p1, Vector3 p2, Vector3 p3);
RayCollision rl_get_ray_collision_quad(Ray ray, Vector3 p1, Vector3 p2, Vector3 p3, Vector3 p4);
void rl_init_audio_device(void);
void rl_close_audio_device(void);
bool rl_is_audio_device_ready(void);
void rl_set_master_volume(float volume);
float rl_get_master_volume(void);
Wave rl_load_wave(const char *fileName);
Wave rl_load_wave_from_memory(const char *fileType, const unsigned char *fileData, int dataSize);
bool rl_is_wave_valid(Wave wave);
Sound rl_load_sound(const char *fileName);
Sound rl_load_sound_from_wave(Wave wave);
Sound rl_load_sound_alias(Sound source);
bool rl_is_sound_valid(Sound sound);
void rl_update_sound(Sound sound, const void *data, int frameCount);
void rl_unload_wave(Wave wave);
void rl_unload_sound(Sound sound);
void rl_unload_sound_alias(Sound alias);
bool rl_export_wave(Wave wave, const char *fileName);
bool rl_export_wave_as_code(Wave wave, const char *fileName);
void rl_play_sound(Sound sound);
void rl_stop_sound(Sound sound);
void rl_pause_sound(Sound sound);
void rl_resume_sound(Sound sound);
bool rl_is_sound_playing(Sound sound);
void rl_set_sound_volume(Sound sound, float volume);
void rl_set_sound_pitch(Sound sound, float pitch);
void rl_set_sound_pan(Sound sound, float pan);
Wave rl_wave_copy(Wave wave);
void rl_wave_crop(Wave *wave, int initFrame, int finalFrame);
void rl_wave_format(Wave *wave, int sampleRate, int sampleSize, int channels);
void rl_unload_wave_samples(float *samples);
Music rl_load_music_stream(const char *fileName);
Music rl_load_music_stream_from_memory(const char *fileType, const unsigned char *data, int dataSize);
bool rl_is_music_valid(Music music);
void rl_unload_music_stream(Music music);
void rl_play_music_stream(Music music);
bool rl_is_music_stream_playing(Music music);
void rl_update_music_stream(Music music);
void rl_stop_music_stream(Music music);
void rl_pause_music_stream(Music music);
void rl_resume_music_stream(Music music);
void rl_seek_music_stream(Music music, float position);
void rl_set_music_volume(Music music, float volume);
void rl_set_music_pitch(Music music, float pitch);
void rl_set_music_pan(Music music, float pan);
float rl_get_music_time_length(Music music);
float rl_get_music_time_played(Music music);
AudioStream rl_load_audio_stream(unsigned int sampleRate, unsigned int sampleSize, unsigned int channels);
bool rl_is_audio_stream_valid(AudioStream stream);
void rl_unload_audio_stream(AudioStream stream);
void rl_update_audio_stream(AudioStream stream, const void *data, int frameCount);
bool rl_is_audio_stream_processed(AudioStream stream);
void rl_play_audio_stream(AudioStream stream);
void rl_pause_audio_stream(AudioStream stream);
void rl_resume_audio_stream(AudioStream stream);
bool rl_is_audio_stream_playing(AudioStream stream);
void rl_stop_audio_stream(AudioStream stream);
void rl_set_audio_stream_volume(AudioStream stream, float volume);
void rl_set_audio_stream_pitch(AudioStream stream, float pitch);
void rl_set_audio_stream_pan(AudioStream stream, float pan);
void rl_set_audio_stream_buffer_size_default(int size);
void rl_set_audio_stream_callback(AudioStream stream, AudioCallback callback);
void rl_attach_audio_stream_processor(AudioStream stream, AudioCallback processor);
void rl_detach_audio_stream_processor(AudioStream stream, AudioCallback processor);
void rl_attach_audio_mixed_processor(AudioCallback processor);
void rl_detach_audio_mixed_processor(AudioCallback processor);

#endif /* SNAKE_RL_H */
