#ifndef SNAKE_RLM_H
#define SNAKE_RLM_H

/* -- raymath.h -- */
#include <raymath.h>

float rl_clamp(float value, float min, float max);
float rl_lerp(float start, float end, float amount);
float rl_normalize(float value, float start, float end);
float rl_remap(float value, float inputStart, float inputEnd, float outputStart, float outputEnd);
float rl_wrap(float value, float min, float max);
int rl_float_equals(float x, float y);
Vector2 rl_vector2_zero(void);
Vector2 rl_vector2_one(void);
Vector2 rl_vector2_add(Vector2 v1, Vector2 v2);
Vector2 rl_vector2_add_value(Vector2 v, float add);
Vector2 rl_vector2_subtract(Vector2 v1, Vector2 v2);
Vector2 rl_vector2_subtract_value(Vector2 v, float sub);
float rl_vector2_length(Vector2 v);
float rl_vector2_length_sqr(Vector2 v);
float rl_vector2_dot_product(Vector2 v1, Vector2 v2);
float rl_vector2_cross_product(Vector2 v1, Vector2 v2);
float rl_vector2_distance(Vector2 v1, Vector2 v2);
float rl_vector2_distance_sqr(Vector2 v1, Vector2 v2);
float rl_vector2_angle(Vector2 v1, Vector2 v2);
float rl_vector2_line_angle(Vector2 start, Vector2 end);
Vector2 rl_vector2_scale(Vector2 v, float scale);
Vector2 rl_vector2_multiply(Vector2 v1, Vector2 v2);
Vector2 rl_vector2_negate(Vector2 v);
Vector2 rl_vector2_divide(Vector2 v1, Vector2 v2);
Vector2 rl_vector2_normalize(Vector2 v);
Vector2 rl_vector2_transform(Vector2 v, Matrix mat);
Vector2 rl_vector2_lerp(Vector2 v1, Vector2 v2, float amount);
Vector2 rl_vector2_reflect(Vector2 v, Vector2 normal);
Vector2 rl_vector2_min(Vector2 v1, Vector2 v2);
Vector2 rl_vector2_max(Vector2 v1, Vector2 v2);
Vector2 rl_vector2_rotate(Vector2 v, float angle);
Vector2 rl_vector2_move_towards(Vector2 v, Vector2 target, float maxDistance);
Vector2 rl_vector2_invert(Vector2 v);
Vector2 rl_vector2_clamp(Vector2 v, Vector2 min, Vector2 max);
Vector2 rl_vector2_clamp_value(Vector2 v, float min, float max);
int rl_vector2_equals(Vector2 p, Vector2 q);
Vector2 rl_vector2_refract(Vector2 v, Vector2 n, float r);
Vector3 rl_vector3_zero(void);
Vector3 rl_vector3_one(void);
Vector3 rl_vector3_add(Vector3 v1, Vector3 v2);
Vector3 rl_vector3_add_value(Vector3 v, float add);
Vector3 rl_vector3_subtract(Vector3 v1, Vector3 v2);
Vector3 rl_vector3_subtract_value(Vector3 v, float sub);
Vector3 rl_vector3_scale(Vector3 v, float scalar);
Vector3 rl_vector3_multiply(Vector3 v1, Vector3 v2);
Vector3 rl_vector3_cross_product(Vector3 v1, Vector3 v2);
Vector3 rl_vector3_perpendicular(Vector3 v);
float rl_vector3_length(const Vector3 v);
float rl_vector3_length_sqr(const Vector3 v);
float rl_vector3_dot_product(Vector3 v1, Vector3 v2);
float rl_vector3_distance(Vector3 v1, Vector3 v2);
float rl_vector3_distance_sqr(Vector3 v1, Vector3 v2);
float rl_vector3_angle(Vector3 v1, Vector3 v2);
Vector3 rl_vector3_negate(Vector3 v);
Vector3 rl_vector3_divide(Vector3 v1, Vector3 v2);
Vector3 rl_vector3_normalize(Vector3 v);
Vector3 rl_vector3_project(Vector3 v1, Vector3 v2);
Vector3 rl_vector3_reject(Vector3 v1, Vector3 v2);
void rl_vector3_ortho_normalize(Vector3 *v1, Vector3 *v2);
Vector3 rl_vector3_transform(Vector3 v, Matrix mat);
Vector3 rl_vector3_rotate_by_quaternion(Vector3 v, Quaternion q);
Vector3 rl_vector3_rotate_by_axis_angle(Vector3 v, Vector3 axis, float angle);
Vector3 rl_vector3_move_towards(Vector3 v, Vector3 target, float maxDistance);
Vector3 rl_vector3_lerp(Vector3 v1, Vector3 v2, float amount);
Vector3 rl_vector3_cubic_hermite(Vector3 v1, Vector3 tangent1, Vector3 v2, Vector3 tangent2, float amount);
Vector3 rl_vector3_reflect(Vector3 v, Vector3 normal);
Vector3 rl_vector3_min(Vector3 v1, Vector3 v2);
Vector3 rl_vector3_max(Vector3 v1, Vector3 v2);
Vector3 rl_vector3_barycenter(Vector3 p, Vector3 a, Vector3 b, Vector3 c);
Vector3 rl_vector3_unproject(Vector3 source, Matrix projection, Matrix view);
float3 rl_vector3_to_float_v(Vector3 v);
Vector3 rl_vector3_invert(Vector3 v);
Vector3 rl_vector3_clamp(Vector3 v, Vector3 min, Vector3 max);
Vector3 rl_vector3_clamp_value(Vector3 v, float min, float max);
int rl_vector3_equals(Vector3 p, Vector3 q);
Vector3 rl_vector3_refract(Vector3 v, Vector3 n, float r);
Vector4 rl_vector4_zero(void);
Vector4 rl_vector4_one(void);
Vector4 rl_vector4_add(Vector4 v1, Vector4 v2);
Vector4 rl_vector4_add_value(Vector4 v, float add);
Vector4 rl_vector4_subtract(Vector4 v1, Vector4 v2);
Vector4 rl_vector4_subtract_value(Vector4 v, float add);
float rl_vector4_length(Vector4 v);
float rl_vector4_length_sqr(Vector4 v);
float rl_vector4_dot_product(Vector4 v1, Vector4 v2);
float rl_vector4_distance(Vector4 v1, Vector4 v2);
float rl_vector4_distance_sqr(Vector4 v1, Vector4 v2);
Vector4 rl_vector4_scale(Vector4 v, float scale);
Vector4 rl_vector4_multiply(Vector4 v1, Vector4 v2);
Vector4 rl_vector4_negate(Vector4 v);
Vector4 rl_vector4_divide(Vector4 v1, Vector4 v2);
Vector4 rl_vector4_normalize(Vector4 v);
Vector4 rl_vector4_min(Vector4 v1, Vector4 v2);
Vector4 rl_vector4_max(Vector4 v1, Vector4 v2);
Vector4 rl_vector4_lerp(Vector4 v1, Vector4 v2, float amount);
Vector4 rl_vector4_move_towards(Vector4 v, Vector4 target, float maxDistance);
Vector4 rl_vector4_invert(Vector4 v);
int rl_vector4_equals(Vector4 p, Vector4 q);
float rl_matrix_determinant(Matrix mat);
float rl_matrix_trace(Matrix mat);
Matrix rl_matrix_transpose(Matrix mat);
Matrix rl_matrix_invert(Matrix mat);
Matrix rl_matrix_identity(void);
Matrix rl_matrix_add(Matrix left, Matrix right);
Matrix rl_matrix_subtract(Matrix left, Matrix right);
Matrix rl_matrix_multiply(Matrix left, Matrix right);
Matrix rl_matrix_multiply_value(Matrix left, float value);
Matrix rl_matrix_translate(float x, float y, float z);
Matrix rl_matrix_rotate(Vector3 axis, float angle);
Matrix rl_matrix_rotate_x(float angle);
Matrix rl_matrix_rotate_y(float angle);
Matrix rl_matrix_rotate_z(float angle);
Matrix rl_matrix_rotate_xyz(Vector3 angle);
Matrix rl_matrix_rotate_zyx(Vector3 angle);
Matrix rl_matrix_scale(float x, float y, float z);
Matrix rl_matrix_frustum(double left, double right, double bottom, double top, double nearPlane, double farPlane);
Matrix rl_matrix_perspective(double fovY, double aspect, double nearPlane, double farPlane);
Matrix rl_matrix_ortho(double left, double right, double bottom, double top, double nearPlane, double farPlane);
Matrix rl_matrix_look_at(Vector3 eye, Vector3 target, Vector3 up);
float16 rl_matrix_to_float_v(Matrix mat);
Quaternion rl_quaternion_add(Quaternion q1, Quaternion q2);
Quaternion rl_quaternion_add_value(Quaternion q, float add);
Quaternion rl_quaternion_subtract(Quaternion q1, Quaternion q2);
Quaternion rl_quaternion_subtract_value(Quaternion q, float sub);
Quaternion rl_quaternion_identity(void);
float rl_quaternion_length(Quaternion q);
Quaternion rl_quaternion_normalize(Quaternion q);
Quaternion rl_quaternion_invert(Quaternion q);
Quaternion rl_quaternion_multiply(Quaternion q1, Quaternion q2);
Quaternion rl_quaternion_scale(Quaternion q, float mul);
Quaternion rl_quaternion_divide(Quaternion q1, Quaternion q2);
Quaternion rl_quaternion_lerp(Quaternion q1, Quaternion q2, float amount);
Quaternion rl_quaternion_nlerp(Quaternion q1, Quaternion q2, float amount);
Quaternion rl_quaternion_slerp(Quaternion q1, Quaternion q2, float amount);
Quaternion rl_quaternion_cubic_hermite_spline(Quaternion q1, Quaternion outTangent1, Quaternion q2, Quaternion inTangent2, float t);
Quaternion rl_quaternion_from_vector3_to_vector3(Vector3 from, Vector3 to);
Quaternion rl_quaternion_from_matrix(Matrix mat);
Matrix rl_quaternion_to_matrix(Quaternion q);
Quaternion rl_quaternion_from_axis_angle(Vector3 axis, float angle);
void rl_quaternion_to_axis_angle(Quaternion q, Vector3 *outAxis, float *outAngle);
Quaternion rl_quaternion_from_euler(float pitch, float yaw, float roll);
Vector3 rl_quaternion_to_euler(Quaternion q);
Quaternion rl_quaternion_transform(Quaternion q, Matrix mat);
int rl_quaternion_equals(Quaternion p, Quaternion q);
Matrix rl_matrix_compose(Vector3 translation, Quaternion rotation, Vector3 scale);
void rl_matrix_decompose(Matrix mat, Vector3 *translation, Quaternion *rotation, Vector3 *scale);

#endif /* SNAKE_RLM_H */
